remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
title: Stephen Young
description: Software Engineer II | M.S. in Artificial Intelligence Candidate, University of Texas at Austin 
header_pages:
  - projects.md