url: https://stephenswyoung.github.io
baseurl: ""  


remote_theme: mmistakes/minimal-mistakes


minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

# Author box
author:
  name: Stephen Young
  avatar: /assets/images/author-box/headshot.png
  bio: "Hi, I am currently a Software Engineer II @ Walmart Global Tech. I graduated from the University of Texas at Austin with a B.S. in Electrical and Computer Engineering in 2024. I am currently pursuing a Master's Degree in AI from the University of Texas at Austin while I work. I am interested in Machine Learning, AI, and Network Theory."

# Header masthead links come from _data/navigation.yml

