title: Stephen Young
description: Software Engineer
url: https://stephenswyoung.github.io
baseurl: ""  


remote_theme: mmistakes/minimal-mistakes


minimal_mistakes_skin: default

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

# Author box
author:
  name: Stephen Young
  avatar: /assets/images/author-box/headshot.jpg
  bio: "Software Engineer II @ Walmart Global Tech."

# Header masthead links come from _data/navigation.yml

